osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os: osx

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

install:
  - npm i

script:
  - ./travis.sh

branches:
  only:
    - /^master-deploy-.*$/
    - /^check-deploy-.*$/ # 用于审核的tag
    - /^beta-deploy-.*$/