name: Build-release

on:
  push:
    tags:
      - 'release-*'

jobs:
  release:
    name: release release-rishiqing-pc
    runs-on: ubuntu-latest
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@v4
      # step2: install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - run: pnpm config set registry https://npm.timetask.cn/
      - run: echo ${{ secrets.NPM_TOKEN }} >> ~/.npmrc
      # step3: install node env
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: pnpm
      # step5: release
      - name: Release
        run: pnpm run deploy 
        env:
          ALY_OSS_ACCESS_ID: ${{ secrets.ALY_OSS_ACCESS_ID }}
          ALY_OSS_ACCESS_KEY: ${{ secrets.ALY_OSS_ACCESS_KEY }}